name: Test and Deploy
on: 
 push: 
  branches:
    -main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v2

      - name: Setup Postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: test_db
          postgresql user: Mr_test
          postgresql password: password1

      - name: Install dependencies
        run: npm install
      - name: Test App.js
        run: PGDATABASE=test_db PGUSER=MR_test PGPASSWORD=password1 npm test
  
  deploy:
    runs-on: ubuntu-latest
    needs: Test App.js
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}